data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
data2 <- subset(data, data$Date == "1/2/2007"|data$Date == "2/2/2007")
data2$Datetime <-paste(data2$Date, data2$Time)
data2$Date <- as.Date(data2$Date, "%d/%m/%Y")
data2$Time <- strptime(data2$Time, "%T")
data2$Global_active_power <- with(data2, as.numeric(Global_active_power))
png("plot2.png", 480, 480)
plot(strptime(data2$Datetime, "%d/%m/%Y %H:%M:%S"), data2$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(Kilowatts)")
dev.off()